WITH DATES AS (
    SELECT ID,
           CASE 
                WHEN MONTH(DIFFERENTIATION_DATE) <= 3 AND MONTH(DIFFERENTIATION_DATE) >= 1 THEN '1Q'
                WHEN MONTH(DIFFERENTIATION_DATE) <= 6 AND MONTH(DIFFERENTIATION_DATE) >= 4 THEN '2Q'
                WHEN MONTH(DIFFERENTIATION_DATE) <= 9 AND MONTH(DIFFERENTIATION_DATE) >= 7 THEN '3Q'
                WHEN MONTH(DIFFERENTIATION_DATE) <= 12 AND MONTH(DIFFERENTIATION_DATE) >= 10 THEN '4Q'
            END AS QUARTER
    FROM ECOLI_DATA
)
SELECT QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM DATES
GROUP BY QUARTER
ORDER BY QUARTER;

       
      