WITH RESULTS AS (
    SELECT ID,
           YEAR(DIFFERENTIATION_DATE) AS YEAR,
           MAX(SIZE_OF_COLONY) OVER (PARTITION BY(YEAR(DIFFERENTIATION_DATE))) AS MAX_SIZE,
           SIZE_OF_COLONY
    FROM ECOLI_DATA
)
SELECT YEAR, MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM RESULTS
ORDER BY YEAR, YEAR_DEV;