SELECT ID, FISH_NAME, LENGTH
FROM FISH_NAME_INFO N
JOIN FISH_INFO I
ON N.FISH_TYPE = I.FISH_TYPE
WHERE I.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO F
    WHERE N.FISH_TYPE = F.FISH_TYPE
)
ORDER BY ID;